---
- name: AAP installation bundle download
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: download AAP
      include_role:
        name: ../../roles/aap_download

- name: AAP Controller pre-install preparations
  hosts: 'all'
  become: yes
  become_method: sudo
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  vars:
    dns_type: none
    controllerinstall: true
    code_server: true
    username: student
    student: "{{ username }}"
#  vars_files:
#    - /tmp/aap_extra_vars.yml

  tasks:
#  - name: set SELinux to permissive
#    ansible.posix.selinux:
#      policy: targeted
#      state: permissive
#    tags:
#     - pre_task

#  - name: set hostname
#    hostname:
#      name: satellite.example.com
#    tags:
#     - pre_task

#  - name: update IPv4 /etc/hosts
#    copy:
#      dest: "/etc/hosts"
#      content: |
#        127.0.0.1 satellite.example.com satellite localhost localhost.localdomain localhost4 localhost4.localdomain4
#        ::1 satellite.example.com satellite localhost localhost.localdomain localhost6 localhost6.localdomain6
#   tags:
#      - pre_task

#  - name: preserve hostname
#    copy:
#      dest: /etc/cloud/cloud.cfg.d/01_hostname.cfg
#      content: |
#        manage_etc_hosts: true
#        preserve_hostname: true
#       fqdn: satellite.example.com
#    tags:
#      - pre_task

  - name: remove rhui repos
    yum:
      name: rh-amazon-rhui-client*
      state: removed
    tags:
      - pre_task

  - name: configure product-id.conf
    copy:
      dest: /etc/yum/pluginconf.d/product-id.conf
      content: |
        [main]
        enabled=1
    tags:
      - pre_taskSat

  - name: subscription manager - register system
    community.general.redhat_subscription:
      state: present
      activationkey: "{{ rhel_activation_key }}"
      org_id: "{{ org_id }}"
    tags:
      - pre_task

  - name: enable repositories
    ansible.builtin.lineinfile:
      path: /etc/rhsm/rhsm.conf
      regexp: '^manage_repos ='
      line: manage_repos = 1
    tags:
      - pre_task

  - name: installer repos
    community.general.rhsm_repository:
      name:
        - rhel-8-for-x86_64-baseos-rpms
        - rhel-8-for-x86_64-appstream-rpms
      state: enabled
      purge: yes
    tags:
      - pre_task

  - name: Update all packages
    yum:
      name: "*"
      state: latest

#### configure automation controller node
  - name: print out ansible_host var
    debug:
      var: hostvars.controller
  - name: print ipv4 address
    debug:
      var: ansible_default_ipv4.address
  - include_role:
      name: ../../roles/user_accounts
  - include_role:
      name: ../../roles/common
  - include_role:
      name: ../../roles/connectivity_test
  - include_role:
      name: ../../roles/common
  - include_role:
      name: ../../roles/control_node
  - include_role:
      name: ../../roles/code_server
#### end automation controller node configuration

  - name: unregister
    community.general.redhat_subscription:
      state: absent

  - name: remove any persistent udev rules
    file:
      path: /etc/udev/rules.d/70-persistent-net.rules
      state: absent
 
  - name: remove HWADDR MAC line from ifcfg-eth0
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      state: absent
      regexp: '^HWADDR'

  - name: build ssh_host_ file list from wildcard
    find:
      paths: /etc/ssh
      patterns: "^ssh_host_"
      use_regex: true
    register: ssh_host_files_to_delete

  - name: remove ssh_host_ files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ ssh_host_files_to_delete.files }}"
